version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7400:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  client:
    build:
      context: ./Messenger.Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
